# Generated by Django 6.0.5 on 2026-05-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=120, unique=True, verbose_name='Название семьи')),
                ('password', models.CharField(max_length=255, verbose_name='Хеш пароля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('Доход', 'Доход'), ('Расход', 'Расход')], default='Расход', max_length=20, verbose_name='Тип')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.familyaccount')),
            ],
            options={
                'unique_together': {('family', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.TextField(verbose_name='Email')),
                ('role', models.CharField(choices=[('Администратор', 'Администратор'), ('Участник', 'Участник')], default='Участник', max_length=30, verbose_name='Роль')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='budget.familyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('exchange_rate_to_rub', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Курс к рублю')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='budget.familyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Доход', 'Доход'), ('Расход', 'Расход')], default='Расход', max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма в рублях')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.familyaccount')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.familymember')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.wallet')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Лимит на месяц')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='budget.category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='budget.familyaccount')),
            ],
            options={
                'unique_together': {('family', 'category')},
            },
        ),
    ]
